[package]
name = "Tricoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
rayon = "1.10.0"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
thiserror = "2.0.9"
trust-dns-resolver = "0.23.2"
